### ISSUE TITLE
F-Droid submission

### ISSUE THREAD

**Issue by avuton** [PaperAirplane-Dev-Team/GigaGet#1]
I love this project, and I've been looking for something FOSS to fill this need, but I never saw it in F-Droid, so I assumed it didn't exist. I'd love it if someone would submit it, or I could submit a request; but I wanted to mention it here first to keep from possible conflicting project keys.

**Comment by xavieryao** [comment]
@fython that rocks!

发自我的 iPhone

**Comment by PeterCxy** [comment]
In fact, I myself is not an F-Droid user :)

**Comment by fython** [comment]
@xavieryao what means....

**Comment by PeterCxy** [comment]
submitted.

https://f-droid.org/forums/topic/gigaget-download-manager/

**Comment by avuton** [comment]
Thanks a ton, I had intention to work on this today. This app really was a missing piece of the puzzle for my Androids. Again, thanks!
