### ISSUE TITLE
Support single treaded fallback mode when HTTP PARTIAL CONTENT is not supported.

### ISSUE THREAD

**Issue by avuton** [PaperAirplane-Dev-Team/GigaGet#12]
While downloading [a pdf](https://www.google.com/url?sa=t&source=web&rct=j&ei=tjdjVdWIKtivoQTPs4CoDQ&url=http://info.networkfleet.com/rs/networkfleet/images/Installation_Policy.pdf&ved=0CCoQFjAB&usg=AFQjCNE3dFv6cjNmEKffFe_hJyZGQCHEAg&sig2=RTSSzZB1F1xlQ3KyUT1rmg) the download fails with server unsupported. As you can see, this is even after degrading to a mono-thread download. If there is other information that might be useful about this use case, please don't hesitate to ask.

![screenshot_2015-05-25-07-53-01](https://cloud.githubusercontent.com/assets/396546/7798764/2366f84a-02b3-11e5-85b8-9b1a5021f6d9.png)

**Comment by PeterCxy** [comment]
GigaGet currently does not support downloading from servers that do not respond to HTTP PARTIAL CONTENT(206) which is the basis of multi-threading and pausing.

**Comment by avuton** [comment]
Oh, that makes sense. Don't want to gum up the issue tracker with unwanted feature requests, but, I would turn this issue into a feature request for a fallback mode.

**Comment by PeterCxy** [comment]
Yes, it may be implemented in the future.

**Comment by PeterCxy** [comment]
implemented.
