### ISSUE TITLE
intent not working correctly

### ISSUE THREAD

**Issue by m1ga** [PaperAirplane-Dev-Team/GigaGet#14]
Nexus 4
Android 5.1

If I click a link (mp3) in Chrome it will just show me Chrome and VLC. Gigaget should be listed there too.

something like:

```
<intent-filter>
            <action android:name="android.intent.action.VIEW" />

            <category android:name="android.intent.category.BROWSABLE" />
            <category android:name="android.intent.category.DEFAULT" />

            <data
                android:host="*"
                android:pathPattern=".*.mp3"
                android:scheme="http" />
        </intent-filter>
```

but for all files (haven't tested it!)

**Comment by PeterCxy** [comment]
Android won't send all intents to custom downloader. That's a system limit. In the next major release we will add a interface to receive share intents instead of trying to catch ACTION_VIEW.

**Comment by m1ga** [comment]
:+1: sounds great! Looking forward to the next release, saw it already got pushed
