### ISSUE TITLE
Take downloads from browser

### ISSUE THREAD

**Issue by thewhitetulip** [PaperAirplane-Dev-Team/GigaGet#16]
I think there are no intent defined for this app, that is why when I download anything from the browser, it is not transferred to gigaget, it would be nice to not have to manually create a download each time you want to download something.

p.s. I see that the app has updated in google play store, but it hasn't updated in F-Droid

**Comment by PeterCxy** [comment]
It used to do catch intents, but unfortunately Android does not send all intents to it. Now it accepts Share actions from browser. I have noticed the F-Droid managers to do updates and they say it will be updated tonight.

**Comment by thewhitetulip** [comment]
Okay, before I came across this download manager, I used to use ADM and it catches every damn download intent, it would be nice for gigaget to do the same, let's see when f-droid managers update the app

**Comment by PeterCxy** [comment]
I think GigaGet is now not stable enough to take all downloads. Maybe we'll try to do this when it is stable enough.

**Comment by thewhitetulip** [comment]
Okay

**Comment by SweetLion** [comment]
That sounds cool ☺
Do the intents support the Firefox browser, too? 
When I click on Download at http://www.clipconverter.cc/download/ZhMM3YPZ/158707343/ e. g. I can choose Firefox and my music app; GigaGet does not appear in the list.  
Thank you very much for your awesome app!

**Comment by PeterCxy** [comment]
@SweetLion For now you can't choose it, however, you can "share" the download page to the GigaGet downloader, then click the link inside GigaGet.

**Comment by thewhitetulip** [comment]
Or you can directly go to gigaget and in options go to the internal browser, it is the best way

**Comment by thewhitetulip** [comment]
was this fixed?

**Comment by PeterCxy** [comment]
@thewhitetulip no, it's wontfix for now.
