### ISSUE TITLE
download/upload speed

### ISSUE THREAD

**Issue by ali-libre** [PaperAirplane-Dev-Team/GigaGet#18]
Hi
I can finally use this under android5
A problem have happen to me or another while they have tow or more network
Then the upload and download of all network will sum together( or select one of them)
ie:3g +hotspot to my notebook
Only my nb are download but i have exactly upload like download speed( u:431 d:431)
My phone use 3g &download 431k ,upload them to notebook &then i have 431k upload
If it will be tow graph while i have 3g/wifi-hotspit or bt-hotspot
Thanks....

**Comment by PeterCxy** [comment]
Do you mean you want to download via 3g & wifi in parallel?

**Comment by PeterCxy** [comment]
Oh I got it, do you mean you want a independent graph for both 3g/WiFi? If so, you could consult the Data Usage page in Android Settings. This issue is closed, if there is any misunderstanding, please just re-open and make a comment.

**Comment by ali-libre** [comment]
I opened a issue wrong here sorry...
