### ISSUE TITLE
Please update GigaGet.

### ISSUE THREAD

**Issue by abbasnaqdi** [PaperAirplane-Dev-Team/GigaGet#35]
Hello . Please update your download manager GigaGet.
This app has not been updated for a long time and a lot of problems. Please fix reported problems.
Please update your GigaGet source.

thank you .

**Comment by Kavan72** [comment]
Right Please update

**Comment by PeterCxy** [comment]
Sorry, but I have to say that this project is no longer maintained from now.

**Comment by Kavan72** [comment]
ok but any other download manager app like this but i need download manager source code for my app
