### ISSUE TITLE
flvxz api

### ISSUE THREAD

**Issue by ghost** [PaperAirplane-Dev-Team/GigaGet#4]
You mention flvxz api in the about dialog; could you elaborate on this? Will building the app from source / without the api key make the app crash/not work in any way or is it all dealt with?

**Comment by Harry-Chen** [comment]
Actually we removed flvxz api in the last major version because of its unclear license.
You can build this app from source without any problem with gradle 2.2.1.

**Comment by Harry-Chen** [comment]
@PeterCxy Just don't forget to modify the content of `about`

**Comment by Harry-Chen** [comment]
Anyway if there is an necessity we'll reconsider to re-write and re-add the API in the future.

**Comment by ghost** [comment]
Thanks for pointing out, I was just curious.
