### ISSUE TITLE
fc on another type link

### ISSUE THREAD

**Issue by ali-libre** [PaperAirplane-Dev-Team/GigaGet#5]
if you go on this page &tap on download you  can  see that the first link will grab &denpendence of link format it will got fc
Sorry  for bad  english
Just test this link to understand
cds.cern.ch/record/1950575

**Comment by Vdragon** [comment]
I have similar issue but not sure exactly
link: https://forja.cenatic.es/plugins/scmgit/cgi-bin/gitweb.cgi?p=supergrub2/supergrub2.git;a=blob_plain;f=po/sgrub.pot;h=a5221715339330edaa6a1a7f74c13fdcf2fbd869;hb=refs/tags/2.02s3

**Comment by PeterCxy** [comment]
Got it.
